#!/bin/bash

#!/bin/bash
#SBATCH --mail-type=ALL
#SBATCH --mail-user=
#SBATCH --job-name=create_db_3

module load R/3.5.0

srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus WBcel235 Caenorhabditis_elegans
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus CanFam3.1 Canis_familiaris
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus KH Ciona_intestinalis
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus GRCz11 Danio_rerio
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus BDGP6 Drosophila_melanogaster
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus Galgal5 Gallus_gallus
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus GRCh38 Homo_sapiens
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus Mmul_8.0 Macaca_mulatta
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default UMD3.1 Bos_taurus TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans CanFam3.1 Canis_familiaris
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans KH Ciona_intestinalis
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans GRCz11 Danio_rerio
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans BDGP6 Drosophila_melanogaster
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans Galgal5 Gallus_gallus
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans GRCh38 Homo_sapiens
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans Mmul_8.0 Macaca_mulatta
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default WBcel235 Caenorhabditis_elegans TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris KH Ciona_intestinalis
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris GRCz11 Danio_rerio
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris BDGP6 Drosophila_melanogaster
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris Galgal5 Gallus_gallus
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris GRCh38 Homo_sapiens
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris Mmul_8.0 Macaca_mulatta
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default CanFam3.1 Canis_familiaris TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default KH Ciona_intestinalis GRCz11 Danio_rerio
srun Rscript ortholog_finding.R default KH Ciona_intestinalis BDGP6 Drosophila_melanogaster
srun Rscript ortholog_finding.R default KH Ciona_intestinalis Galgal5 Gallus_gallus
srun Rscript ortholog_finding.R default KH Ciona_intestinalis GRCh38 Homo_sapiens
srun Rscript ortholog_finding.R default KH Ciona_intestinalis Mmul_8.0 Macaca_mulatta
srun Rscript ortholog_finding.R default KH Ciona_intestinalis monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default KH Ciona_intestinalis GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default KH Ciona_intestinalis Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default KH Ciona_intestinalis Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default KH Ciona_intestinalis R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default KH Ciona_intestinalis FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default KH Ciona_intestinalis TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio BDGP6 Drosophila_melanogaster
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio Galgal5 Gallus_gallus
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio GRCh38 Homo_sapiens
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio Mmul_8.0 Macaca_mulatta
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default GRCz11 Danio_rerio TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster Galgal5 Gallus_gallus
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster GRCh38 Homo_sapiens
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster Mmul_8.0 Macaca_mulatta
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default BDGP6 Drosophila_melanogaster TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus GRCh38 Homo_sapiens
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus Mmul_8.0 Macaca_mulatta
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default Galgal5 Gallus_gallus TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default GRCh38 Homo_sapiens Mmul_8.0 Macaca_mulatta
srun Rscript ortholog_finding.R default GRCh38 Homo_sapiens monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default GRCh38 Homo_sapiens GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default GRCh38 Homo_sapiens Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default GRCh38 Homo_sapiens Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default GRCh38 Homo_sapiens R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default GRCh38 Homo_sapiens FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default GRCh38 Homo_sapiens TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default Mmul_8.0 Macaca_mulatta monDom5 Monodelphis_domestica
srun Rscript ortholog_finding.R default Mmul_8.0 Macaca_mulatta GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default Mmul_8.0 Macaca_mulatta Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default Mmul_8.0 Macaca_mulatta Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default Mmul_8.0 Macaca_mulatta R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default Mmul_8.0 Macaca_mulatta FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default Mmul_8.0 Macaca_mulatta TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default monDom5 Monodelphis_domestica GRCm38 Mus_musculus
srun Rscript ortholog_finding.R default monDom5 Monodelphis_domestica Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default monDom5 Monodelphis_domestica Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default monDom5 Monodelphis_domestica R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default monDom5 Monodelphis_domestica FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default monDom5 Monodelphis_domestica TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default GRCm38 Mus_musculus Pan_tro_3.0 Pan_troglodytes
srun Rscript ortholog_finding.R default GRCm38 Mus_musculus Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default GRCm38 Mus_musculus R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default GRCm38 Mus_musculus FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default GRCm38 Mus_musculus TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default Pan_tro_3.0 Pan_troglodytes Rnor_6.0 Rattus_norvegicus
srun Rscript ortholog_finding.R default Pan_tro_3.0 Pan_troglodytes R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default Pan_tro_3.0 Pan_troglodytes FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default Pan_tro_3.0 Pan_troglodytes TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default Rnor_6.0 Rattus_norvegicus R64-1-1 Saccharomyces_cerevisiae
srun Rscript ortholog_finding.R default Rnor_6.0 Rattus_norvegicus FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default Rnor_6.0 Rattus_norvegicus TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default R64-1-1 Saccharomyces_cerevisiae FUGU4 Takifugu_rubripes
srun Rscript ortholog_finding.R default R64-1-1 Saccharomyces_cerevisiae TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R default FUGU4 Takifugu_rubripes TETRAODON8 Tetraodon_rubripes
srun Rscript ortholog_finding.R plant TAIR10 Arabidopsis_thaliana Gm02 Glycine_max
srun Rscript ortholog_finding.R plant TAIR10 Arabidopsis_thaliana IRGSP-1.0 Oryza_sativa
srun Rscript ortholog_finding.R plant TAIR10 Arabidopsis_thaliana AGPv4 Zea_mays
srun Rscript ortholog_finding.R plant Gm02 Glycine_max IRGSP-1.0 Oryza_sativa
srun Rscript ortholog_finding.R plant Gm02 Glycine_max AGPv4 Zea_mays
srun Rscript ortholog_finding.R plant IRGSP-1.0 Oryza_sativa AGPv4 Zea_mays
srun Rscript ortholog_finding.R metazoa AgamP4 Anopheles_gambiae Amel_4.5 Apis_mellifera
srun Rscript ortholog_finding.R metazoa AgamP4 Anopheles_gambiae WBcel235 Caenorhabditis_elegans
srun Rscript ortholog_finding.R metazoa AgamP4 Anopheles_gambiae BDGP6 Drosophila_melanogaster
srun Rscript ortholog_finding.R metazoa AgamP4 Anopheles_gambiae ASM20922v1 Nematostella_vectensis
srun Rscript ortholog_finding.R metazoa Amel_4.5 Apis_mellifera WBcel235 Caenorhabditis_elegans
srun Rscript ortholog_finding.R metazoa Amel_4.5 Apis_mellifera BDGP6 Drosophila_melanogaster
srun Rscript ortholog_finding.R metazoa Amel_4.5 Apis_mellifera ASM20922v1 Nematostella_vectensis
srun Rscript ortholog_finding.R metazoa WBcel235 Caenorhabditis_elegans BDGP6 Drosophila_melanogaster
srun Rscript ortholog_finding.R metazoa WBcel235 Caenorhabditis_elegans ASM20922v1 Nematostella_vectensis
srun Rscript ortholog_finding.R metazoa BDGP6 Drosophila_melanogaster ASM20922v1 Nematostella_vectensis
srun Rscript ortholog_finding.R fungi R64-1-1 Saccharomyces_cerevisiae ASM294v2 Schizosaccharomyces_pombe
